### PR TITLE
Add earliest supported RuboCop CI check

### LINKED ISSUE #283: Add build step to CI for running rubocop-rspec against rubocop on master
Running tests with `gem 'rubocop', git: 'https://github.com/bbatsov/rubocop.git'` would probably help detect breakages

### PR DESCRIPTION
**Pull request by pirj**
Add a job to be making sure the changes in pull requests are still compatible with the earliest supported RuboCop version.

For `earliest-supported-rubocop` job `bundle install` step reports:
```
Fetching rubocop 0.68.1
Installing rubocop 0.68.1
```

Fixes #283

- [ ] make the check mandatory on GitHub

---

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [-] Added tests.
* [-] Added an entry to the [changelog](https://github.com/rubocop-hq/rubocop-rspec/blob/master/CHANGELOG.md) if the new code introduces user-observable changes.
* [-] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

File: .circleci/config.yml [hunk 1]
```diff
@@ -61,6 +61,32 @@ jobs:
...
+
+  earliest-supported-rubocop:
+    docker:
+      - image: circleci/ruby
+    steps:
+      - checkout
+      - run:
+          name: Use earliest supported RuboCop
+          command: |
+            echo "gem 'rubocop', '0.68.1'" > Gemfile.local
```
Comment (bquorning) [inline .circleci/config.yml]: Our gemspec says `spec.add_runtime_dependency 'rubocop', '>= 0.60.0'`, so I would imaging we should install `0.60.0` here. Where does the `0.68.1` come from?

Comment (bquorning) [reply .circleci/config.yml]: Ah, from #804 probably.

It would be nice if we could write this version number dynamically, e.g.:
```
ruby -e "version = File.read('rubocop-rspec.gemspec')[/^  spec\.add_runtime_dependency 'rubocop', '>= (\d+\.\d+\.\d+)'$/, 1]; File.write('Gemfile.local', %(gem 'rubocop', '#{version}'))"
```

**Comment by pirj** [comment]
No surprise, but it seems at least our specs do not work with 0.60.0 specified in the Gemfile:
```
       NoMethodError:
         undefined method `expect_correction' for #<RSpec::ExampleGroups::RuboCopCopRSpecInstanceSpy::WhenUsedWithHaveReceived:0x00007fb5b0eaa660>
         Did you mean?  expect_offense

...
1254 examples, 119 failures
```

`expect_correction` first appeared in 0.63.0.

I suggest merging #804 first.

**Comment by bquorning** [comment]
> No surprise, but it seems at least our specs do not work with 0.60.0 specified in the Gemfile:

I think this is actually a good case for not including the “earliest supported RuboCop“ in the test suite: The `lib` code may well be compatible with the old rubocop version, but the `spec` code may not – and won’t need to be.

I have been playing with the idea of extracting different parts of rubocop, rubocop-performance, rubocop-rails and this project into a rubocop-dev gem. If that were realised, we might be able to reliably test against the earliest supported version of RuboCop.

**Comment by pirj** [comment]
That makes total sense to me, even though it's a bit strange to use different supported versions of RuboCop as development and runtime dependencies.

**Comment by bquorning** [comment]
Could we split this PR in two? I’d like to think some more on the “earliest” part, but “edge” is ready to merge.

**Comment by pirj** [comment]
@bquorning Fair enough.
Please check this out #821.

**Comment by pirj** [comment]
So, to summarize the problem at hand.
Cops should be compatible with the earliest version of RuboCop we claim to support.
At the same time, we want to use the latest spec helpers in the spec helper code that newer versions provide (e.g. `expect_offense`).
The two should not necessarily depend on each other, at least I'm not aware of the implications.

The idea was to extract spec helpers/shared examples/etc to `rubocop-dev` and be less conservative regarding its version, since it's only for CI/development, while continue to be as conservative as possible with supported `rubocop` version, and only update the dependency when necessary (like #804). Is that correct, @bquorning ?
You also mentioned there are parts in `rubocop-performance`, `rubocop-rails`, and `rubocop-rspec` that might find its shelter in `rubocop-dev`. What parts would that be?

WDYT if we start small and extract spec helpers and shared examples to `rubocop-dev`, use the latest features from it without looking back? I can tackle this.

**Comment by bquorning** [comment]
> WDYT if we start small and extract spec helpers and shared examples to `rubocop-dev`, use the latest features from it without looking back? I can tackle this.

Sounds good. We should perhaps involve the rubocop core team too.

**Comment by pirj** [comment]
Since there's no definitive conclusion on this topic, and RuboCop 1.0 is on the horizon with its more conservative cop introduction policy, I believe that following minor `rubocop` versions won't be a problem.
With this in mind, I'd rather close this.
