### ISSUE TITLE
Does not work with latest Rubocop 0.25

### ISSUE THREAD

**Issue by pkuczynski** [rubocop-hq/rubocop-rspec#22]
Here is an error which I get running `rubocop -d`:

```
undefined local variable or method `path' for RuboCop::RSpec::Inject:Module
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/gems/rubocop-rspec-1.1.0/lib/rubocop/rspec/inject.rb:16:in `defaults!'
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/gems/rubocop-rspec-1.1.0/lib/rubocop-rspec.rb:9:in `<top (required)>'
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/gems/rubocop-0.25.0/lib/rubocop/config_loader.rb:43:in `require'
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/gems/rubocop-0.25.0/lib/rubocop/config_loader.rb:43:in `block in load_file'
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/gems/rubocop-0.25.0/lib/rubocop/config_loader.rb:43:in `each'
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/gems/rubocop-0.25.0/lib/rubocop/config_loader.rb:43:in `load_file'
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/gems/rubocop-0.25.0/lib/rubocop/config_loader.rb:97:in `configuration_from_file'
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/gems/rubocop-0.25.0/lib/rubocop/config_store.rb:40:in `for'
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/gems/rubocop-0.25.0/lib/rubocop/target_finder.rb:59:in `target_files_in_dir'
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/gems/rubocop-0.25.0/lib/rubocop/target_finder.rb:29:in `find'
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/gems/rubocop-0.25.0/lib/rubocop/runner.rb:47:in `find_target_files'
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/gems/rubocop-0.25.0/lib/rubocop/runner.rb:18:in `run'
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/gems/rubocop-0.25.0/lib/rubocop/cli.rb:24:in `run'
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/gems/rubocop-0.25.0/bin/rubocop:13:in `block in <top (required)>'
/Users/kuczynsk/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/gems/rubocop-0.25.0/bin/rubocop:12:in `<top (required)>'
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/bin/rubocop:23:in `load'
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/bin/rubocop:23:in `<main>'
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/bin/ruby_executable_hooks:15:in `eval'
/Users/kuczynsk/.rvm/gems/ruby-2.1.2@izumi/bin/ruby_executable_hooks:15:in `<main>'
```
